name: dnd-sed
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - loguru=0.3.2=py37_1
  - numpy=1.17.4=py37hc1035e2_0
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pyyaml=5.1.2=py37h7b6447c_0

